#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { version } = require('./package.json');

fs.writeFileSync(
  path.resolve(__dirname, 'lib/sdkVersion.ts'),
  `// autogenerated by prebuild.js
  export const TENDERLY_SDK_VERSION = '${version}';
`,
);
